### ISSUE TITLE
rettungssimulator.online/script/* von 404-Seite ausnehmen

### ISSUE THREAD

**Issue by Notme112** [Rettungssimulator/ReSi-Community#11]
Würde es deutlich leichter machen, eigene Frames zu erstellen bzw. man könnte halt das Script dann speziell auf diesen Include auslegen, wie z.B. /scripts/nizi112/notes. Erstmal wäre das ganze dann von den Includes immer aktuell wenn ihr euren Head da einbindet, und dann funktioniert auch so nen Kram wie z.B. Frame neu laden oder so. Danke 😊

**Comment by LennardTFD** [comment]
Wurde umgesetzt
Es existiert die neue Unterseite `/script` (singular)
Wenn sie im Format `/script/<author>` oder `/script/<author>/<scriptName>` aufgerufen wird, bietet sich eine leere Seite mit den standard iFrame includes.

Über die Selektoren `#scriptTitle` und `#scriptDescription` können der Titel und die Unterschrift im iFrame Header direkt editiert werden.
