### ISSUE TITLE
Socket: newChatMessage

### ISSUE THREAD

**Issue by NiZi112** [Rettungssimulator/ReSi-Community#2]
# Socket Request

**Endpunkt Name**
newChatMessage

**Funktionsbeschreibung**
Wird ausgelöst, wenn es eine neue Chatnachricht gibt.

- [x] Rückgabe von Daten
- [ ] Ändern von Spieldaten

**Nutzen des Endpunkts**
Ich würde gerne in der Codebase einen kleinen Alarm einbauen

```kein Code, da Socket```

**Comment by Ron31** [comment]
Hey @NiZi112! Dein Socket existiert so bereits im Code unter:
"associationMessage", und liefert ein messageObject in folgenden Formen zurück:
Verbandbeitritt: *Man beachte systemMessage*
`{
    "associationChatMessageID": 33495,
    "systemMessage": "<b>Scripter</b> hat den Verband betreten",
    "colorClass": "success",
    "createdAt": "2021-06-06 11:21:30"
}`
Verbandverlassen: *auch hier beachte man systemMessage*
`{
    "associationChatMessageID": 33497,
    "systemMessage": "<b>Scripter</b> hat den Verband verlassen",
    "colorClass": "danger",
    "createdAt": "2021-06-06 11:21:44"
}`
Verbandnachricht: *hier steht dann nur message, also das für dich spannende*
`{
    "associationChatMessageID": 33496,
    "userName": "Scripter",
    "message": "test",
    "roleColor": "",
    "roleName": "",
    "createdAt": "2021-06-06 11:21:39"
}`

**Comment by NiZi112** [comment]
Ah, ja, kann es sein, dass dazu noch kein Wiki-Eintrag existiert? Alternativ kann es auch sein, dass ich den übersehen habe...

**Comment by Ron31** [comment]
Es existiert kein Wikibeitrag, da die erst mit der association dazu gekommen ist, und seitdem das nicht mehr geupdated wurde ^^

**Comment by LennardTFD** [comment]
Sockets in d321da2 geupdated und ergänzt.
https://github.com/Rettungssimulator/ReSi-Community/wiki/Socket%20associationMessage

**Comment by NiZi112** [comment]
Gut, danke euch beiden

**Comment by Notme112** [comment]
Kann nochmal einer die Labels evnt. anpassen?
