### ISSUE TITLE
API: /buildings

### ISSUE THREAD

**Issue by TheKeineAhnung** [Rettungssimulator/ReSi-Community#3]
# API Request

**Endpunkt Name**
/api/buildings

**Funktionsbeschreibung**
Rückgabe von Informationsdaten von Gebäuden

- [x] Rückgabe von Daten

**Nutzen des Endpunkts**
Nutzung der Daten in meinem Script zum Gebäude zählen. Würde mir das manuelle ergänzen von Gebäuden nach Update sparen. Generell auch mit den Informationen in anderen Scripten nutzbar.

**Anfrage Parameter**

**Antwort Daten**

`1` -> buildingType des Gebäudes
`departmentName` -> Name der im Shop angezeigt wird
`organizationName` -> Name der Organisation der der Wache angehört
`organizationID` -> Id der Organisation der die Wache angehört
`maxLevel` -> Maximale Ausbaustufe
`defaultPersonal` -> Standardmäßige Anzahl an Personal auf der Wache
`defaultMuenzen` -> Standardkosten (Münzen)
`defaultMarken` -> Standardkosten (Marken)
`description` -> Beschreibung die im Shop angezeigt wird
`markerName` -> Name des Markers der auf der Karte verwendet wird
`buildingCategory` -> Kategorie des Gebäudes (school/department/controlCenter)
`generates` -> Lässt das Gebäude Einsätze generieren?

*Welche Daten erhälst du als Antwort?*

- [x] JSON

```json
{
  1: {
    "departmentName": "Feuerwache",
    "organizationName": "Feuerwehr",
    "organizationID": 1,
    "maxLevel": 10,
    "defaultPersonal": 12,
    "defaultMuenzen": 75000,
    "defaultMarken": 50,
    "description": "Stellplatz für Feuerwehrfahrzeuge",
    "markerName": "fireDepartment",
    "buildingCategory": "department",
    "generates": true
  }
}
```

**Comment by LennardTFD** [comment]
```json
[
  {
    "buildingID"       : int,
    "buildingName"     : string,
    "buildingCategory" : string,
    "description"      : string,
    "organisationID"   : int,
    "organisationName" : string,
    "defaultPersonal"  : int,
    "defaultMuenzen"   : int,
    "defaultMarken"    : int,
    "maxLevel"         : int,
    "markerName"       : string,
    "canGenerate"      : bool
  }
]
```

Dies wird die zu erwartende Struktur sein. Ebenfalls wird es möglich sein bestimme BuildingIDs optional direkt anzusprechen `/api/buildings/{buildingID}`.
